import type { ThemeConfig } from 'antd';

export const tokens: ThemeConfig['token'] = {
  colorPrimary: '#1A1A1A',
  colorInfo: '#17324F',
  colorLink: '#17324F',
  borderRadius: 8,
  borderRadiusSM: 6,
  borderRadiusLG: 14,
  colorBgLayout: '#FAFAFA',
  colorBgContainer: '#FFFFFF',
  colorBgElevated: '#FFFFFF',
  colorBorder: '#E5E7EB',
  colorBorderSecondary: '#E5E7EB',
  colorSplit: '#EFEFF1',
  colorText: '#111827',
  colorTextSecondary: '#6B7280',
  colorTextTertiary: '#9CA3AF',
  colorTextLightSolid: '#FFFFFF',
  colorFillTertiary: '#F2F2F3',
  fontSizeHeading3: 28,
  fontWeightStrong: 700,
  controlHeight: 40,
  controlHeightLG: 44,
  boxShadowSecondary: '0 1px 2px rgba(17,24,39,0.04)',
};
